from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from services.agent_engine import agent_engine

router = APIRouter(prefix="/api/agents", tags=["Autonomous Clinical Agents"])

class ScanRequest(BaseModel):
    agent_id: str
    topic: str

@router.get("/roster")
async def get_agent_roster():
    """Returns the list of active autonomous research agents."""
    return {"agents": agent_engine.get_agents()}

@router.get("/hypotheses")
async def get_agent_hypotheses():
    """Returns all klinical hypotheses generated by the agent network."""
    return {"hypotheses": agent_engine.get_hypotheses()}

@router.post("/scan")
async def trigger_agent_scan(req: ScanRequest):
    """Commands an agent to scan literature and formulate a new federated job."""
    result = agent_engine.trigger_agent_scan(req.agent_id, req.topic)
    if "error" in result:
        raise HTTPException(status_code=404, detail=result["error"])
    return result

@router.post("/approve/{hyp_id}")
async def approve_hypothesis(hyp_id: str):
    """Human-in-the-loop approval to launch an agent's proposed training ring."""
    result = agent_engine.approve_hypothesis(hyp_id)
    if "error" in result:
        raise HTTPException(status_code=404, detail=result["error"])
    return result
